#!/usr/bin/env node
import { chmod, writeFile } from "node:fs/promises";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { defaultEnvPath, loadEnvFile } from "./env.js";
import { defaultModelingArgs, defaultModelingCommand } from "./modelingBinary.js";

async function main() {
  loadEnvFile();

  const rl = createInterface({ input, output });
  try {
    console.log("Power BI MCP setup");
    console.log(`Env file: ${defaultEnvPath()}`);
    console.log("");

    const modelingCommandDefault =
      process.env.POWERBI_MODELING_MCP_COMMAND ||
      defaultModelingCommand();
    const modelingCommand = await prompt(rl, "Microsoft Modeling MCP command", modelingCommandDefault);
    const modelingArgs = await prompt(
      rl,
      "Microsoft Modeling MCP args",
      process.env.POWERBI_MODELING_MCP_ARGS || defaultModelingArgs(modelingCommand).join(" ")
    );
    const knownWorkspaces = await prompt(
      rl,
      "Known workspace names, comma-separated",
      process.env.POWERBI_KNOWN_WORKSPACES || process.env.POWERBI_DEFAULT_WORKSPACE || ""
    );
    const defaultWorkspace = await prompt(rl, "Default CEO workspace", process.env.POWERBI_DEFAULT_WORKSPACE || firstCsvValue(knownWorkspaces));
    const defaultSemanticModel = await prompt(rl, "Default CEO semantic model, optional fallback", process.env.POWERBI_DEFAULT_SEMANTIC_MODEL || "");

    const lines = [
      "# Generated by npm run setup",
      `POWERBI_MODELING_MCP_COMMAND=${quote(modelingCommand)}`,
      `POWERBI_MODELING_MCP_ARGS=${quote(modelingArgs)}`,
      knownWorkspaces ? `POWERBI_KNOWN_WORKSPACES=${quote(knownWorkspaces)}` : undefined,
      defaultWorkspace ? `POWERBI_DEFAULT_WORKSPACE=${quote(defaultWorkspace)}` : undefined,
      defaultSemanticModel ? `POWERBI_DEFAULT_SEMANTIC_MODEL=${quote(defaultSemanticModel)}` : undefined,
      ""
    ].filter((line): line is string => line !== undefined);

    await writeFile(defaultEnvPath(), lines.join("\n"), { mode: 0o600 });
    await chmod(defaultEnvPath(), 0o600);

    console.log("");
    console.log("Saved .env. Run `npm run build` then `npm start` or point Claude to dist/server.js.");
  } finally {
    rl.close();
  }
}

async function prompt(rl: ReturnType<typeof createInterface>, label: string, defaultValue: string): Promise<string> {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = (await rl.question(`${label}${suffix}: `)).trim();
  return answer || defaultValue;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function firstCsvValue(value: string): string {
  return value.split(",").map(item => item.trim()).find(Boolean) || "";
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
